## Assingment 3 fra the python bois


2. create a function to read the csv file containing Copenhagen city population data and return a numpy array (numpy.ndarray). hint: use np.genfromtxt(filename, delimiter=',', dtype=np.uint, skip_header=1) as in the slides

In [2]:
import numpy as np
pop_array = np.genfromtxt('befkbhalderstatkode.csv', delimiter=',', dtype=np.uint, skip_header=1)
print(pop_array)

[[2015    1    0 5100  614]
 [2015    1    0 5104    2]
 [2015    1    0 5106    1]
 ...
 [1992   99   89 5100    1]
 [1992   99   90 5180    1]
 [1992   99   93 5100    1]]


3. create a function that can extract the number of all the citizens from native english speaking countries and from non english speaking countries.
How many are there of each? (hint remember that with python you can return multiple values from a function).

In [11]:
import numpy as np
def get_population(look_up_list, land_code, year):
    population = 0
    for i in range(len(land_code)):
        population = look_up_list[(look_up_list[:,3] == land_code[i]) & (look_up_list[:,0] == year)]
        
    return population.sum()



In [10]:
pop_array = np.genfromtxt('befkbhalderstatkode.csv', delimiter=',', dtype=np.uint, skip_header=1)
lands = [5160, 5170, 5120, 5130]
print(get_population(pop_array, lands, 2015))


0
1
2
3
4194167


4. Now create another function that can take 2 arguments:

 - 1: the dataset in the form of a 2dimensional data array where y=data rows and x=[year, area, age nationality, amount].

 - 2: the mask in the form: data[:,3] == 5120 to find swedish or data[:,0] == 1999 to filter on year

 - 3:the return value must be the filtered dataset.

5. Create another function that can take 2 arguments:

 - a dataset with same characteristics as above and

 - a value for the x-axis (either year, area, age or nationality)

 - return value should be the accumulated population for all x-values.

 - hint: if year is chosen for x then y is all accumulated amounts from all areas, ages and nationalities.

6. Create Illustration 1: In your notebook use the above function and create a 2d array of year as x and accumulated amount as y:
  - create a line graph of the population change over time for all of Copenhagen

7. Create illustration 2: In your notebook use your module to create a dataset where development of all German citizens can be shown over time

8. Create illustration 3: Show a bar plot of all the 18-25 year old in the different areas of copenhagen and in the same plot show (in a different color) all 60-67 year old in the different areas.

9. Create illustration 4: show a pie chart of age groups (0-10, 10-20, 20-30 ...) in Østerbro part of Copenhagen. create another similar piechart for Vesterbro.